### ISSUE TITLE
Repeat button

### ISSUE THREAD

**Issue by VincentVolmer** [actionwatcher/MorseCodeX#25]
Repeat button (F6 like in QRQ/RufZ) repeats a callsign or the send phrase with max 'retries' fixed, custom or none.

(sorry, don't know if this is the right place for this request)

**Comment by actionwatcher** [comment]
Vincent, 
Thank you and yes, this is correct place. 

<F6> for repeat will go into v1.0 release but I will need some time to figure out how to make it configurable in a user friendly way

**Comment by actionwatcher** [comment]
Implemented keyboard mapping that at this point support only mapping Repeats to <F6> by default. This value is user configurable. 
commit: e83c9
